sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_0930996c5c07_key -iv $encrypted_0930996c5c07_iv
  -in .env.enc -out Backend/.env -d
- docker build -t poko91/designflow:$(git rev-parse HEAD) -f Backend/Dockerfile Backend
script:
- docker run --rm -p 3000:3000 -e CI=true -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY poko91/designflow:$(git rev-parse
  HEAD) npm test
